version: "3.3"
services:

      
  mymongo:
    image: mongo:latest
    container_name: 'mymongo'
    ports:
     - "27017:27017"
    privileged: True
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - '/data/configdb:/data/configdb'
      - '/data/db:/data/db'
    networks:
      - mynet

  mongo_admin:
    image: mongo-express
    container_name: 'mongoadmin'
    depends_on:
     - mymongo
    links:
     - mymongo
    ports:
     - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/?authSource=admin
      # ME_CONFIG_MONGODB_URL: mongodb://localhost:27017
      ME_CONFIG_MONGODB_SERVER: mymongo
      # - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      # - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    networks:
      - mynet
    volumes:
      - ./data:/data/db
  
  # mycomposer:
  #   image: composer/composer
  #   container_name: 'mycontainer'
    
  #   networks: 
  #     - mynet


  myphp:
    container_name: myphp
    depends_on:
      # - mysql
      # - myredis
      - mymongo
    build:
      context: ./src/php
      dockerfile: dockerfile
    privileged: True
    expose:
      - 9000
    volumes:
      - "./src:/var/www/html"
    networks:
      - mynet

  mynginx:
    container_name: mynginx
    depends_on:
      - myphp
      - mymongo
    image: nginx:latest
    ports:
      - "8080:80"
    privileged: True
    volumes:
      - "./src:/var/www/html"
      - "./src/nginx.ini:/etc/nginx/conf.d/default.conf"
    networks:
      - mynet

  # phpMyAdmin:
  #   container_name: phpMyAdmin
  #   image: phpmyadmin:latest
  #   environment:
  #     PMA_HOST: mysql
  #   ports: 
  #     - "8082:80"
  #   privileged: True
  #   networks: 
  #     - mynet

networks: 
  mynet: 
    driver: bridge
