# FROM php:7.4-fpm

# RUN pecl install igbinary \
# 	&& pecl install redis \
# 	&& docker-php-ext-install mysqli \
# 	&& docker-php-ext-enable redis \
# 	&& echo "extension=redis.so" > /usr/local/etc/php/conf.d/redis.ini




# https://docs.bitnami.com/tutorials/create-custom-php-fpm-container-mongodb-support/

FROM php:7.4-fpm
RUN apt-get update && apt-get install -y autoconf build-essential
RUN pecl install mongodb
RUN echo "extension=mongodb.so" >> /opt/local/php/etc/php.ini